language: rust

services:
  - docker

matrix:
  include:
    # Stable channel.
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      osx_image: xcode11.4 # Catalina
      rust: stable
      env: TARGET=x86_64-apple-darwin

    # Beta channel.
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu

    # Minimum Rust supported channel.
    - os: linux
      rust: 1.49.0
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: 1.49.0
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      rust: 1.49.0
      env: TARGET=x86_64-apple-darwin

sudo: required

env:
  global:
    # Default target on travis-ci.
    # Used as conditional check in the install stage
    - HOST=x86_64-unknown-linux-gnu
    # Used on the deployment script
    - PROJECT_NAME=rpatchur

before_install:
  - bash ci/before_install.sh

install:
  # prevent target re-add error from rustup
  - if [[ $TRAVIS_OS_NAME = linux && $HOST != $TARGET ]]; then rustup target add $TARGET; fi

script:
  - bash ci/script.sh

before_deploy:
  - bash ci/before_deploy.sh

deploy:
  provider: releases
  # NOTE updating the `api_key.secure`
  # - go to: https://github.com/settings/tokens/new
  # - generate new token using `public_repo` scope
  # - encrypt it using: `travis encrypt API_KEY_HERE`
  # - paste the output below
  api_key:
    secure: "bQc8cZSMpmLfO5yBauHNITo+ifnzDwEhmZ8atLD15wb6JyYmgM7Nzw5/wu5ng1VhHafKAAtBA4Z9SKgG4+Uvb24z9PCH1KgGuJ77wH555aHW4LGAz5o333CGW4Y934KjiAmwUlZsECrwYqRkGyW+XGrD6jpw6TyH/1UFqhPk3QT8ZWiH9xFPsgv08NZt4pwlh5bQVcN8y+FOwvl947n/KdWyQUrxI6r88l4vhfUr8w1j66UKiS2pw8oiDKxsuF2He4vOIranjdktQzLXJ667taFYZi6eqw3u5ijoXsipLZFWjnP7oKNO4tctBZj5i5+i/vnf8nqGowoVeMOYCoLldt+kJ6o43/ltqOQlLVLr6FKAhWAQeDfu611/xECiKyhq8LDHdY+HOODwz9WER8iZMjMPMA+LAjZWbgPA3HJtTfi4wkRouWX8rcr3PGIXOSfNuWWMNRwTnUTbnuQxB2yU/UkA6m2FV7Hz21KII0RX9z5j9QG/y6zk1YVO8jnXlqFS3ONtocvcpeYZlGlVEAfTFw9cv04yFYZIfTeYGZFG/XvfLdO8g6mP92WrkKkOj78DEpc0fdECzLavLdBHQ/u9ELID03jAJC0HoZY/P/6hwdYXOrLwRgEb1iO+i5pkgRbpSF15xRwSEC5normqJMYz6qZglemeKCgxGv04XA2j3JY="
  # for uploading multiple files
  file_glob: true
  # NOTE explanation on each env variable
  # - PROJECT_NAME: name of the project, set on the `env.global` above
  # - TRAVIS_TAG: tag name that the build is being deployed for, usually the version number
  # - TARGET: target triple of the build
  file:
    - $PROJECT_NAME-$TRAVIS_TAG-$TARGET.*
  # don't delete artifacts from previous stage
  skip_cleanup: true
  on:
    # deploy only if we push a tag
    tags: true
    # deploy only on stable channel that has TARGET env variable sets
    condition: $TRAVIS_RUST_VERSION = stable && $TARGET != ""

notifications:
  email:
    on_success: never

