[package]
name = "rpatchur"
version = "0.1.0"
authors = ["LinkZ <wanthost@gmail.com>"]
edition = "2018"

[dependencies]
web-view = { version = "0.5.4" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.10", features = ["blocking"] }
url = "2.1"
tempfile = "3"
tar = "0.4"